#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Data Explorations # The title of the book. Will be placed in the left navbar.
author                      : V&A - Digital Media & Publishing  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : va-red.png  # A path to the book logo
repository:
        url:    https://github.com/vanda/etc-docs/
        path_to_book: notebooks/data-explorations/
html:
        use_repository_button: true
        use_issues_button: true
        use_edit_page_button: true

only_build_toc_files: true
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/d3/6.6.2/d3.min.js


execute:
    timeout: 120
